spring.datasource.url=jdbc:mysql://localhost:3306/hyundai_shop
spring.datasource.username=root
spring.datasource.password=Lionel&2324

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

stripe.secret.key=${STRIPE_SECRET_KEY}